use_frameworks!

target 'ACRadioPlayer_ios' do
  platform :ios, '10.0'
  pod 'ACRadioPlayer', :path => '../'

  target 'ACRadioPlayer_Tests' do
    inherit! :complete

  end
end

target 'ACRadioPlayer_SwiftUI' do
  platform :ios, '14.0'
  pod 'ACRadioPlayer', :path => '../'
end

target 'ACRadioPlayer_mac' do
  platform :osx, '10.12'
  pod 'ACRadioPlayer', :path => '../'
end

target 'ACRadioPlayer_tvOS' do
  platform :tvos, '10.0'
  pod 'ACRadioPlayer', :path => '../'
end
