name: ACRadioPlayer
options:
  bundleIdPrefix: com.fethica
  deploymentTarget:
    iOS: 10.0
    macOS: 10.12
    tvOS: 10.0
targets:
  ACRadioPlayer:
    type: framework
    platform: [iOS]
    sources: Sources/ACRadioPlayer
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
  ACRadioPlayer_mac:
    type: framework
    platform: [macOS]
    sources: Sources/ACRadioPlayer
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
  ACRadioPlayer_tvOS:
    type: framework
    platform: [tvOS]
    sources: Sources/ACRadioPlayer
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
